---
- name: "Set Defaults"
  shell: "defaults {{ item.extra | default('') }} write {{ item.key }} -{{ item.type }} {{ item.value }}; sleep 2;"
  with_items: "{{ settings }}"
  when: settings is defined

- name: "Restart Applications"
  shell: "Killall {{ item }}"
  with_items: "{{ restartAfter }}"
  when: restartAfter is defined