---
- hosts: all
  roles:

  # Install Applications
  
  - name: "Install Homebrew"
    role: Homebrew

  - name: "Install CLI Applications via Homebrew"
    role: brew_package
    packages:
      - openssl
      - docker
      - wget
      - curl
      - git
      - hub
      - mas
      - gpg-agent
      - httpie
      - speedtest_cli
      - zsh

  # - name: "Install Applications via Homebrew Cask"
  #   role: cask_package
  #   apps:
  #     - google-chrome
  #     - google-drive
  #     - spotify
  #     - sublime-text
  #     - slack
  #     - vlc
  #     - flux
  #     - iterm2
  #     - keybase
  #     - torbrowser
  #     - the-unarchiver
  #     - grammarly


  - name: "Install Applications via App Store"
    role: mas_package
    mas_email: "aaran.mcguire@me.com"
    apps:
      - name: Clocks
        id: 414554506
      - name: VisualDiffer
        id: 412386481
      - name: Twitter
        id: 409789998
      - name: Calca
        id: 635758264
      - name: BetterSnapTool
        id: 417375580

  # User Configuration

  - name: "Install & Setup Oh-My-Zsh"
    role: oh_my_zsh
    config:
      plugins:
        - git
        - dockers
        - httpie
      aliases:
        - { alias: "art", command: "php artisan" }
        - { alias: "git", command: "hub" }
        - { alias: "cask", command: "brew cask" }

  - name: "Set git Configuration"
    role: git_config
    git_user_name: "Aaran McGuire"
    git_user_email: "aaran.mcguire@cl.vc"
    git_user_signingkey: "8062012BABDF0202"
    git_commit_gpgsign: true

  - name: "Configure the Dock"
    role: dock
    apps:
      - "/Applications/Spotify.app"
      - "/Applications/Google Chrome.app"
      - "/Applications/iTerm.app"
    folders:
      - path: "/Applications"
        display: stack
        sort: name

  - name: "Set Defaults"
    role: mac_defaults
    settings:
      # Auto Hide Dock with no delay.
      - { key: "com.apple.Dock autohide-delay", value: 0, type: float }
      - { key: "com.apple.Dock autohide", value: true, type: bool }
      # Dock Sizes.
      - { key: "com.apple.Dock largesize", value: 38, type: float }
      - { key: "com.apple.Dock tilesize", value: 16, type: float }
      # Enable Dock Magnification.
      - { key: "com.apple.Dock magnification", value: 1, type: float }
      # Disable Image import when connecting devices.
      - { key: "com.apple.ImageCapture disableHotPlug", value: true, type: bool }
      # Disable press and hold for foreign characters. 
      - { key: "NSGlobalDomain ApplePressAndHoldEnabled", value: false, type: bool }
      # Disable auto spelling correction.
      - { key: "NSGlobalDomain NSAutomaticSpellingCorrectionEnabled", value: false, type: bool }
      # Ask for password after screensaver.
      - { key: "com.apple.screensaver askForPassword", value: 1, type: int }
      - { key: "com.apple.screensaver askForPasswordDelay", value: 0, type: int }
      # Show HDD on Desktop.
      - { key: "com.apple.finder ShowExternalHardDrivesOnDesktop", value: true, type: bool }
      - { key: "com.apple.finder ShowHardDrivesOnDesktop", value: true, type: bool }
      - { key: "com.apple.finder ShowMountedServersOnDesktop", value: false, type: bool }
      # Show extentions in finder.
      - { key: "NSGlobalDomain AppleShowAllExtensions", value: true, type: bool }
      # Show stats bar in finder.
      - { key: "com.apple.finder ShowStatusBar", value: true, type: bool }
      # Disable warnings when changing file extentions.
      - { key: "com.apple.finder FXEnableExtensionChangeWarning", value: false, type: bool }
      # Disable .DS_Store files on network drives.
      - { key: "com.apple.desktopservices DSDontWriteNetworkStores", value: true, type: bool }
      # Enable text selection in Quicklook.
      - { key: "com.apple.finder QLEnableTextSelection", value: true, type: bool }
      # Disable TimeMachine for external disks.
      - { key: "com.apple.TimeMachine DoNotOfferNewDisksForBackup", value: true, type: bool }
      # Set default finder window to user home folder.
      - { key: "com.apple.finder NewWindowTarget", value: "PfHm", type: string }  
      # When performing a search, search the current folder by default.
      - { key: "com.apple.finder FXDefaultSearchScope", value: "SCcf", type: string }
      # Use column view.
      - { key: "com.apple.finder FXPreferredViewStyle", value: "Nlsv", type: string }
      # Show battery percentage in menu bar
      - { key: "com.apple.menuextra.battery ShowPercent", value: "YES", type: string }
      # Mouse Settings.
      - { key: "NSGlobalDomain AppleEnableSwipeNavigateWithScrolls", value: 0, type: int }
      - { key: "NSGlobalDomain com.apple.trackpad.threeFingerDragGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.threeFingerTapGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.threeFingerVertSwipeGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.twoFingerDoubleTapGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.twoFingerFromRightEdgeSwipeGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.fourFingerVertSwipeGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "com.apple.dock showLaunchpadGestureEnabled", value: false, type: bool }
      # Set F.lux Settings.
      - { key: "org.herf.Flux lateColorTemp", value: 1200, type: int }
      - { key: "org.herf.Flux nightColorTemp", value: 2700, type: int }
      - { key: "org.herf.Flux wakeTime", value: 420, type: int }
      - { key: "org.herf.Flux sleepLate", value: true, type: bool }
      - { key: "org.herf.Flux under18", value: true, type: bool }
    restartAfter:
      - Dock
      - Finder
      - SystemUIServer # Menu Bar
