---
- hosts: all
  roles:

  # Install Applications

  - name: "Install CLI Applications via Homebrew"
    role: brew_package
    packages:
      - openssl
      - openssh
      - docker
      - wget
      - curl
      - git
      - hub
      - mas
      - zsh
      - tor
      - bind
      - jq

  - name: "Install Applications via Homebrew Cask"
    role: cask_package
    apps:
      - google-chrome
      - spotify
      - sublime-text
      - slack
      - vlc
      - iterm2
      - torbrowser
      - the-unarchiver
      - ticktick
      - wechat
      - whatsapp
      - signal
      - visual-studio-code

  - name: "Hide applications if SIP is disabled"
    role: hide_applications
    apps:
      - "/Applications/Chess.app"
      - "/Applications/Automator.app"
      - "/Applications/Contacts.app"
      - "/Applications/Dashboard.app"
      - "/Applications/Dictionary.app"
      - "/Applications/DVD\\ Player.app"
      - "/Applications/Font\\ Book.app"
      - "/Applications/iBooks.app"
      - "/Applications/Image\\ Capture.app"
      - "/Applications/Launchpad.app"
      - "/Applications/Mail.app"
      - "/Applications/Maps.app"
      - "/Applications/Mission\\ Control.app"
      - "/Applications/Photo\\ Booth.app"
      - "/Applications/Reminders.app"
      - "/Applications/Siri.app"
      - "/Applications/Stickies.app"
      - "/Applications/Time\\ Machine.app"

  - name: "Install Applications via App Store"
    role: mas_package
    mas_email: "aaran.mcguire@me.com"
    apps:
      - name: Clocks
        id: 414554506
      - name: BetterSnapTool
        id: 417375580

  # User Configuration

  - name: "Install & Setup Oh-My-Zsh"
    role: oh_my_zsh
    config:
      plugins:
        - git
        - brew
      PATHs:
        - "{{ ansible_env.HOME }}/.composer/vendor/bin" # Composer
        - "/usr/local/sbin" # Homebrew
        - "/usr/local/bin" # Homebrew
        - "{{ ansible_env.HOME }}/Library/Python/2.7/bin" # Ansible/Pip packages
        - "/usr/local/opt/curl/bin" # Homebrew curl
      aliases:
        - { alias: "git", command: "hub" }
        - { alias: "subl", command: "/Applications/Sublime\\ Text.app/Contents/SharedSupport/bin/subl" }

  - name: "Set Git Configuration"
    role: git_config
    git_user_name: "Aaran McGuire"
    git_user_email: "aaran.mcguire@cl.vc"

  - name: "Configure the Dock"
    role: dock
    apps:
      - "/Applications/Spotify.app"
      - "/Applications/iTerm.app"
    folders:
      - path: "/Applications"
        display: stack
        sort: name

  - name: "Set Defaults"
    role: mac_defaults
    settings:
      # Auto Hide Dock with no delay.
      - { key: "com.apple.Dock autohide-delay", value: 0, type: float }
      - { key: "com.apple.Dock autohide", value: true, type: bool }
      # Dock Sizes.
      - { key: "com.apple.Dock largesize", value: 38, type: float }
      - { key: "com.apple.Dock tilesize", value: 16, type: float }
      # Enable Dock Magnification.
      - { key: "com.apple.Dock magnification", value: 1, type: float }
      # Disable Image import when connecting devices.
      - { key: "com.apple.ImageCapture disableHotPlug", value: true, type: bool }
      # Disable press and hold for foreign characters. 
      - { key: "NSGlobalDomain ApplePressAndHoldEnabled", value: false, type: bool }
      # Disable auto spelling correction, auto capitalisation & smart quotes.
      - { key: "NSGlobalDomain NSAutomaticSpellingCorrectionEnabled", value: false, type: bool }
      - { key: "NSGlobalDomain NSAutomaticCapitalizationEnabled", value: false, type: bool }
      - { key: "NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled", value: false, type: bool }
      # Ask for password after screensaver.
      - { key: "com.apple.screensaver askForPassword", value: 1, type: int }
      - { key: "com.apple.screensaver askForPasswordDelay", value: 0, type: int }
      # Show HDD on Desktop.
      - { key: "com.apple.finder ShowExternalHardDrivesOnDesktop", value: true, type: bool }
      - { key: "com.apple.finder ShowHardDrivesOnDesktop", value: true, type: bool }
      - { key: "com.apple.finder ShowMountedServersOnDesktop", value: false, type: bool }
      # Show extentions in finder.
      - { key: "NSGlobalDomain AppleShowAllExtensions", value: true, type: bool }
      # Show stats bar in finder.
      - { key: "com.apple.finder ShowStatusBar", value: true, type: bool }
      # Dont show tags on sidebar.
      - { key: "com.apple.finder ShowRecentTags", value: false, type: bool }
      # Show HHD and Mac Name under Devices.
      - { key: "com.apple.finder SidebarDevicesSectionDisclosedState", value: true, type: bool }
      # Disable warnings when changing file extentions.
      - { key: "com.apple.finder FXEnableExtensionChangeWarning", value: false, type: bool }
      # Disable .DS_Store files on network drives.
      - { key: "com.apple.desktopservices DSDontWriteNetworkStores", value: true, type: bool }
      # Enable text selection in Quicklook.
      - { key: "com.apple.finder QLEnableTextSelection", value: true, type: bool }
      # Disable TimeMachine for external disks.
      - { key: "com.apple.TimeMachine DoNotOfferNewDisksForBackup", value: true, type: bool }
      # Set default finder window to user home folder.
      - { key: "com.apple.finder NewWindowTarget", value: "PfHm", type: string }  
      # When performing a search, search the current folder by default.
      - { key: "com.apple.finder FXDefaultSearchScope", value: "SCcf", type: string }
      # Use column view.
      - { key: "com.apple.finder FXPreferredViewStyle", value: "Nlsv", type: string }
      # Mouse Settings.
      - { key: "NSGlobalDomain AppleEnableSwipeNavigateWithScrolls", value: 0, type: int }
      - { key: "NSGlobalDomain com.apple.trackpad.threeFingerDragGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.threeFingerTapGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.threeFingerVertSwipeGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.twoFingerDoubleTapGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.twoFingerFromRightEdgeSwipeGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "NSGlobalDomain com.apple.trackpad.fourFingerVertSwipeGesture", value: 0, type: int, extra: "-currentHost" }
      - { key: "com.apple.dock showLaunchpadGestureEnabled", value: false, type: bool }
      # Disable Force Touch.
      - { key: "com.apple.AppleMultitouchTrackpad ForceSuppressed", value: true, type: bool }
      - { key: "com.apple.AppleMultitouchTrackpad ActuateDetents", value: 0, type: int }
      # Set click to Firm.
      - { key: "com.apple.AppleMultitouchTrackpad FirstClickThreshold", value: 2, type: int }
      - { key: "com.apple.AppleMultitouchTrackpad SecondClickThreshold", value: 2, type: int }
      # Set Touchbar settings.
      - { key: "com.apple.controlstrip FullCustomized", value: "'com.apple.system.group.brightness' 'com.apple.system.screen-lock' NSTouchBarItemIdentifierFlexibleSpace 'com.apple.system.group.volume' 'com.apple.system.group.media'", type: array }
      - { key: "com.apple.touchbar.agent PresentationModeGlobal", value: "fullControlStrip", type: string }
      - { key: "NSGlobalDomain NSAutomaticTextCompletionEnabled", value: false, type: bool}
      # Disable Dashboard.
      - { key: "com.apple.dashboard mcx-disabled", value: true, type: bool }
      # Disable Dictation hotkey.
      - { key: "com.apple.HIToolbox AppleDictationAutoEnable", value: false, type: bool }
      # Enable zoom.
      - { key: "com.apple.symbolichotkeys AppleSymbolicHotKeys", value: "15 '{enabled = 1;}'", type: dict-add }
      - { key: "com.apple.symbolichotkeys AppleSymbolicHotKeys", value: "17 '{enabled = 1;}'", type: dict-add }
      - { key: "com.apple.symbolichotkeys AppleSymbolicHotKeys", value: "19 '{enabled = 1;}'", type: dict-add }
      - { key: "com.apple.symbolichotkeys AppleSymbolicHotKeys", value: "23 '{enabled = 1;}'", type: dict-add }
      - { key: "com.apple.universalaccess closeViewHotkeysEnabled", value: true, type: bool }
      - { key: "com.apple.universalaccess closeViewScrollWheelToggle", value: true, type: bool }
      - { key: "com.apple.AppleMultitouchTrackpad HIDScrollZoomModifierMask", value: 262144, type: int }
      # Disable Accessibility shortcut.
      - { key: "com.apple.universalaccess feature.dwellControl", value: false, type: bool }
      - { key: "com.apple.universalaccess feature.invertDisplayColor", value: false, type: bool }
      - { key: "com.apple.universalaccess feature.mouseKeys", value: false, type: bool }
      - { key: "com.apple.universalaccess feature.slowKeys", value: false, type: bool }
      - { key: "com.apple.universalaccess feature.stickyKeys", value: false, type: bool }
      - { key: "com.apple.universalaccess feature.switchControl", value: false, type: bool }
      - { key: "com.apple.universalaccess feature.voiceOver", value: false, type: bool }
      - { key: "com.apple.universalaccess feature.zoom", value: false, type: bool }
      # Set menubar.
      - { key: "com.apple.airplay showInMenuBarIfPresent", value: false, type: bool }
      - { key: "com.apple.systemuiserver menuExtras", value: "'/System/Library/CoreServices/Menu Extras/Clock.menu' '/System/Library/CoreServices/Menu Extras/AirPort.menu' '/System/Library/CoreServices/Menu Extras/Volume.menu' '/System/Library/CoreServices/Menu Extras/Battery.menu'", type: array }
    restartAfter:
      - Dock
      - Finder
      - SystemUIServer # Menu Bar
      - ControlStrip # Touch Bar
