---

- name: "Install Composer Packages"
  shell: "composer {{ item.global | default('') | regex_replace('^true$', 'global') }} require {{ item.package | default(item) }}"
  with_items: "{{ packages }}"
  when: packages is defined


  # ToDo: Add Composer upgrade/update