---

- name: "Check if SIP is enabled"
  shell: csrutil status | enabled
  register: is_SIP_enabled
  failed_when: "installed_applications.rc == 2"
  ignore_errors: yes

- name: "Hide applications (SIP is disabled)"
  shell: "chflags hidden {{ item }}"
  with_items: "{{ apps }}"
  when: is_SIP_enabled.rc == 1 and apps is defined
  become: yes