---
# manage dock

- name: "Clear dock"
  shell: "PYTHONIOENCODING=utf-8 {{ dockutil_exe }} --remove all"

- name: "Add Applications"
  shell: "PYTHONIOENCODING=utf-8 {{ dockutil_exe }} --add '{{ item }}'"
  ignore_errors: True
  with_items: "{{ apps }}"

- name: "Add Folders"
  shell: "PYTHONIOENCODING=utf-8 {{ dockutil_exe }} --add '{{ item.path }}' --view {{ item.view|default('grid') }} --display {{ item.display|default('folder') }} --sort {{ item.sort|default('name') }}"
  ignore_errors: True
  with_items: "{{ folders }}"
  when: folders is defined
