---
# installs homebrew system-wide
# let's stat some things and register some conditionals
- name: "Assert Homebrew installation"
  stat:
    path: "{{ brew_install_path }}/bin/brew"
  register: brew_installed

- name: "Install Homebrew"
  git: 
    repo: https://github.com/Homebrew/homebrew
    dest: "{{ brew_repo_path }}"
    update: no
  when: brew_installed.stat.exists == false

- name: "Copy {{ brew_install_path }} to {{ brew_repo_path }}"
  sudo: True
  synchronize:
    src: "{{ brew_install_path }}/"
    dest: "{{ brew_repo_path }}"
    copy_links: yes
  when: brew_installed.stat.exists == false

- name: "Fix user ACL on {{ brew_repo_path }} and clean up {{ brew_install_path }}"
  sudo: True
  file:
    path: "{{ item.path }}"
    state: "{{ item.state|default('directory') }}"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755
  with_items:
    - { path: '{{ brew_repo_path }}' }
    - { path: '{{ brew_repo_path }}/bin' }
    - { path: '{{ brew_install_path }}' , state: 'absent' }
  when: brew_installed.stat.exists == false

- name: "Ensure {{ brew_repo_path }} is linked to the {{ brew_install_path }}"
  sudo: True
  file:
    state: link
    src: "{{ brew_repo_path }}"
    dest: "{{ brew_install_path }}"
    owner: "{{ ansible_user_id }}"
  when: brew_installed.stat.exists == false

- name: "Update Homebrew"
  homebrew: update_homebrew=yes
  when: brew_installed.stat.exists == true
