---

- name: "Assert Homebrew installation"
  stat:
    path: "/usr/local/bin/brew"
  register: brew_installed

- name: "Ensure Homebrew directory exists"
  file:
    path: /usr/local/homebrew
    owner: "{{ ansible_user_id }}"
    group: admin
    state: directory
    recurse: true
    mode: 0775
  become: yes

- name: "Ensure Homebrew directory exists (2)"
  file:
    path: /usr/local/bin
    owner: "{{ ansible_user_id }}"
    group: admin
    state: directory
    recurse: true
    mode: 0775
  become: yes

- name: "Install Homebrew"
  git: 
    repo: "https://github.com/Homebrew/homebrew"
    dest: "/usr/local/homebrew"
    update: no
    accept_hostkey: yes
    depth: 1
  when: brew_installed.stat.exists == false

- name: "Symlink brew to homebrew_brew_bin_path"
  file:
    src: "/usr/local/homebrew/bin/brew"
    dest: "/usr/local/bin/brew"
    state: link
    force: yes
  when: brew_installed.stat.exists == false
  become: yes

- name: "Update Homebrew"
  homebrew:
    update_homebrew: yes
  when: brew_installed.stat.exists == true

- name: "export PATH env"
  shell: 'export PATH="/usr/local/bin:$PATH"'
